version: "3"

services:
  api:
    container_name: 'guide-api'
    build: .
    networks:
      - my-networks
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql:3306/mydb'
      SPRING_DATASOURCE_USERNAME: 'root'
      SPRING_DATASOURCE_PASSWORD: 'verysecret'
    ports:
      - '8080:8080'
  mysql:
    container_name: 'guide-mysql'
    image: 'mysql:latest'
    networks:
      - my-networks
    environment:
      - 'MYSQL_DATABASE=mydb'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
networks:
  my-networks:
    driver: bridge