services:
  mysql:
    container_name: 'efm-mysql'
    image: 'mysql:latest'
    restart: 'always'
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 1.0
    networks:
      - my-networks
    environment:
      - 'MYSQL_DATABASE=mydb'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
  api:
    container_name: 'efm-api'
    build: .
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 1.0
    restart:
      on-failure:3
    networks:
      - my-networks
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql:3306/mydb'
      SPRING_DATASOURCE_USERNAME: 'root'
      SPRING_DATASOURCE_PASSWORD: 'verysecret'
    ports:
      - '8080:8080'
    depends_on:
      - mysql
networks:
  my-networks:
    driver: bridge

volumes:
  mysql_data: